---
name: Build Go Cache

"on":
  workflow_dispatch:


permissions:
  contents: read
  
jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          #ref: ${{ github.event.release.tag_name }}
          ref: v3.2.8
    
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./src/go.mod
          cache: false

#      - name: Set Go cache date
#        shell: bash
#        run: echo "GO_CACHE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      
#      - name: Go Cache Paths
#        id: gocachepaths
#        run: |        
#          echo "gobuild=$(go env GOCACHE)" >> $$GITHUB_OUTPUT
#          echo "go-mod=$(go env GOMODCACHE)" >> $$GITHUB_OUTPUT
          


      - name: Get the current date
        id: date
        run: |
          go env GOMODCACHE
          echo "date=$(TZ='Europe/Berlin' date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "test1=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-cache=$(go env GOCACHE)" >> $$GITHUB_OUTPUT
          echo "go-modcache=$(go env GOMODCACHE)" >> $$GITHUB_OUTPUT

      - name: Output debug informations
        run: |
          echo "${{ steps.date.outputs.date }}"
          echo "${{ steps.date.outputs.test1 }}"
          echo "${{ steps.date.outputs.go-cache }}"
          echo "${{ steps.date.outputs.go-modcache }}"
          
      # Cache go build cache, used to speedup go test
#      - name: Go Build Cache
#        uses: actions/cache@v4
#        with:
#          path: ${{ steps.go-cache-paths.outputs.go-build }}
#          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      
      # Cache go mod cache, used to speedup builds
#      - name: Go Mod Cache
#        uses: actions/cache@v4
#        with:
#          path: ${{ steps.go-cache-paths.outputs.go-mod }}
#          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}          
